name: first
on: push
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Print date
      run: date
    
  job2:
    name: Second job
    runs-on: windows-latest
    needs: job1
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildrenItem Env | Sort-Object Name"
      
  job3:
    name: Third job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildrenItem Env | Sort-Object Name"
      
  job4:
    name: forth job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildrenItem Env | Sort-Object Name"
