name: Python COde

on: [push]

jobs:
  test-e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Choose the Python version you want to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Replace with the name of your requirements file
    - name: Run Python script
      run: python script.py # Replace with the name of your Python script
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
     
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact # Name of the artifact
        path: . # Path to the artifact file or folder
